name: vcpkg

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install necessary packages
        run: sudo apt install -y ninja-build curl libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config autoconf libudev-dev dh-autoreconf freeglut3-dev gdb make

      - uses: actions/checkout@v2.3.4
      
      - name: Setup anew (or from cache) vcpkg (and does not build any package)
        uses: lukka/run-vcpkg@v11
      
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'Linux-release'
          buildPreset: 'Linux-release'
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.workspace }}/out/build/Linux-release/InfraredBrickTower

  # build-windows:
  #   runs-on: windows-latest
  #   steps:
  #     - name: checkout all the submodules
  #       uses: actions/checkout@v2
  #       with:
  #         submodules: recursive
      
  #     - uses: actions/checkout@v2.3.4
      
  #     - name: Setup anew (or from cache) vcpkg (and does not build any package)
  #       uses: lukka/run-vcpkg@v11
        
  #     - name: Add msbuild to PATH
  #       uses: microsoft/setup-msbuild@v1.1
  #       with:
  #         vs-version: '17.8.3'
      
  #     - name: Build driver
  #       run: msbuild ${{ github.workspace }}/InfraredBrickTower.sln -property:Configuration=Release -property:Platform=x64
      
  #     - name: Run CMake
  #       uses: lukka/run-cmake@v10
  #       with:
  #         configurePreset: 'Windows-release'
  #         buildPreset: 'Windows-release'
